channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=23.3.1
- pip:
  - mlflow
  - catboost==1.2.2
  - cloudpickle==2.2.1
  - ipywidgets==7.8.1
  - scikit-learn==1.3.2
  - xgboost==2.0.2
name: mlflow-env
