channels:
- conda-forge
dependencies:
- python=3.9.18
- pip<=23.3.1
- pip:
  - mlflow==2.10.2
  - catboost==1.2.2
  - cloudpickle==3.0.0
  - ipywidgets==8.1.2
  - numpy==1.24.4
  - packaging==23.1
  - pandas==1.5.3
  - psutil==5.9.5
  - pyyaml==5.3.1
  - scikit-learn==1.4.1.post1
  - scipy==1.9.3
  - xgboost==2.0.3
name: mlflow-env
